#version 430 core
layout(local_size_x = 16, local_size_y = 16) in;
struct Ray
{
    vec4 origin;
    vec4 dir;
    float len;
    bool is_shadow_ray;
};

struct AABB 
{
    vec4 p_min;
    vec4 p_max;
};

const float view_plane_dist = 1.733;
const float EPSILON = 0.000001f;
const float GAMMA = 2.2;
float x_ratio = 1.0;
float y_ratio = 1.0;
float z_ratio = 1.0;

AABB bb = AABB(vec4(0, 0, 0, 1), vec4(1, 1, 1, 1));
ivec3 vol_size;
vec4 half_len = vec4(0, 0, 0, 1);

layout(binding = 1, std140) uniform Camera 
{
    mat4 view_mat;
    vec4 eye;
    float view_plane_dist;
} cam;

layout(location = 0) uniform float alpha_scale;
layout(location = 1) uniform vec3 voxel_size;
layout(location = 2) uniform int min_val;
layout(location = 3) uniform int max_val;
layout(location = 4) uniform int is_MIP;
layout(location = 5) uniform int view_top;
layout(location = 6) uniform int view_bottom;

layout(binding = 0, rgba32f) uniform image2D render_texture;
layout(binding = 1) uniform usampler3D vol_tex3D;

void computeRay(float pixel_x, float pixel_y, int img_width, int img_height, out Ray eye_ray);
bool intersectRayAABB(Ray ray, AABB bb, out float t_min, out float t_max);
vec4 rayMarchVolume(Ray eye_ray, float t_min, float t_max);
vec4 MIP(Ray eye_ray, float t_min, float t_max);
vec3 cartesianToTextureCoord(vec4 point);

void main()
 {
    ivec2 img_size = imageSize(render_texture);
    ivec2 pix = ivec2(gl_GlobalInvocationID.xy);
    if(pix.x >= img_size.x || pix.y >= img_size.y) return;
    
    vol_size = textureSize(vol_tex3D, 0);
    int max_dim = max(vol_size.x, vol_size.y);
    max_dim = max(max_dim, vol_size.z);

    if(view_bottom == 1 || view_top == 1)
    {
        bb.p_max = vec4(vol_size.xzy, 1.0);
    } 
    else 
    {
        bb.p_max = vec4(vol_size.xyz, 1.0);
    }

    bb.p_max /= max_dim;
    if(view_bottom == 1 || view_top == 1) 
    {
        bb.p_max *= vec4(voxel_size.xzy, 1.0);
    } 
    else 
    {
        bb.p_max *= vec4(voxel_size.xyz, 1.0);
    }

    half_len = vec4(bb.p_max.xyz * 0.5, 0.0);
    bb.p_min -= half_len;
    bb.p_max -= half_len;

    Ray eye_ray;
    computeRay(pix.x + 0.5, pix.y + 0.5, img_size.x, img_size.y, eye_ray);
    float t_max, t_min;
    if(intersectRayAABB(eye_ray, bb, t_min, t_max))
    {
        vec4 color;
        color = rayMarchVolume(eye_ray, t_min, t_max);
        imageStore(render_texture, pix, color);
    }
    else
    {
        imageStore(render_texture, pix, vec4(0.0f));
    }
}

vec4 rayMarchVolume(Ray eye_ray, float t_min, float t_max) 
{
    float step_size;
    vec4 start_point = eye_ray.origin + (eye_ray.dir * t_min);
    vec4 end_point = eye_ray.origin + (eye_ray.dir * t_max);
    step_size = length(bb.p_max.xyz - bb.p_min.xyz) / length(vol_size.xzy);

    vec4 dest = vec4(0.0);
    vec4 src = vec4(0.0);
    vec4 pos = start_point + eye_ray.dir * EPSILON;

    for(int i = 0; i < 10000;i++)
    {
        vec3 tex_coord = cartesianToTextureCoord(pos);
        if( any(greaterThan(tex_coord, vec3(1.0))) || any(lessThan(tex_coord, vec3(0.0))) || dest.a >= 0.95)
            break;

        src = vec4(texture(vol_tex3D, tex_coord).r);
        src = clamp(src, vec4(min_val), vec4(max_val));
        if(src.a <= max_val && src.a >= min_val)
        {
            src = (src - min_val) / (max_val - min_val);
        }

        src.a *= alpha_scale;
        src.rgb *= src.a;
        dest += src * (1 - dest.a);

        if(dest.a > 0.99)
        {
            break;
        }
        pos += eye_ray.dir * step_size;
    }
    return dest;
}

vec3 cartesianToTextureCoord(vec4 point) 
{
    point += half_len;
    point /= (bb.p_max + half_len);

    point.z = 1 - point.z;
    if(view_top == 1)
    {
        return vec3(point.x, 1 - point.z, point.y);
    } 
    else if(view_bottom == 1) 
    {
        return vec3(point.x, point.z, 1 - point.y);
    } 
    else 
    {
        return point.xyz;
    }
}

void computeRay(float pixel_x, float pixel_y, int img_width, int img_height, out Ray eye_ray) 
{
    float x, y, z, aspect_ratio;
    
    aspect_ratio = (img_width * 1.0) / img_height;
    x = (2.0 * pixel_x / float(img_width) - 1.0) * aspect_ratio;
    y = (2.0 * pixel_y / float(img_height) - 1.0);
    z = - cam.view_plane_dist;

    eye_ray.origin = cam.eye;
    eye_ray.dir = normalize(vec4(x, y, z, 1.0));
    eye_ray.dir = normalize(cam.view_mat * eye_ray.dir);
    eye_ray.len = 99999999.9;
}

bool intersectRayAABB(Ray ray, AABB bb, out float t_min, out float t_max)
{
    t_max = 1.0 / 0.0, t_min = - t_max;
    vec3 dir_inv = 1 / ray.dir.xyz;

    vec3 min_diff = (bb.p_min - ray.origin).xyz * dir_inv;
    vec3 max_diff = (bb.p_max - ray.origin).xyz * dir_inv;

    t_min = max(t_min, min(min_diff.x, max_diff.x));
    t_max = min(t_max, max(min_diff.x, max_diff.x));

    t_min = max(t_min, min(min_diff.y, max_diff.y));
    t_max = min(t_max, max(min_diff.y, max_diff.y));
    if(t_max < t_min) return false;

    t_min = max(t_min, min(min_diff.z, max_diff.z));
    t_max = min(t_max, max(min_diff.z, max_diff.z));

    return (t_max > max(t_min, 0));
}
